### ISSUE TITLE
Handling of multidimensional arrays

### ISSUE THREAD

**Issue by gkastrinis** [secure-software-engineering/tamiflex#2]
Maybe I am doing something wrong but I think the following behavior is a bug.

I have this file
```
cat -n Test1.java 
     1  import java.lang.reflect.Array;
     2
     3  public class Test1
     4  {
     5    public static void main(String[] ps) {
     6                  Test1[] single = (Test1[]) Array.newInstance(Test1.class, 3);
     7
     8                  int[] sizes = {3, 5, 4};
     9                  Test1[][][] multi = (Test1[][][]) Array.newInstance(Test1.class, sizes);
    10                  System.out.println(multi[0].length);
    11    }
    12 
```

And using the poa jar I get among others the following
```
Array.newInstance;Test1;Test1.main;9;;
Array.newInstance;Test1[];Test1.main;6;;
``` 

Is the entry for line 9 a bug?

**Comment by ericbodden** [comment]
Hi George.

Let me see if I understand correctly… Are you wondering whether...

> Array.newInstance;Test1[];Test1.main;6;;

… should instead be:

> Array.newInstance;Test1;Test1.main;6;;

??

Cheers,
Eric

**Comment by gkastrinis** [comment]
Hi Eric. No I am wondering why

> Array.newInstance;Test1;Test1.main;9;;

isn't something like

> Array.newInstance;Test1[][][];Test1.main;9;;

or

> Array.newInstance;Test1;Test1.main;9;dim=3;

**Comment by ericbodden** [comment]
Oh I see. Thanks for clarifying. Yes this might be a bug. I think I simply had not thought about such cases. If I find some time later today I will take a look.

**Comment by gkastrinis** [comment]
Cool. Thanks for your time.

**Comment by ericbodden** [comment]
@gkastrinis This should be fixed now, please rebuild the POA from source.

**Comment by gkastrinis** [comment]
Thanks Eric. It seems to work ok now.
