### ISSUE TITLE
Viewing control graph and transformed classes

### ISSUE THREAD

**Issue by jyotigajrani** [secure-software-engineering/tamiflex#3]
I have done all the steps successfully for Tamiflex using Tutorial:
https://github.com/Sable/soot/wiki/Using-Soot-and-TamiFlex-to-analyze-DaCapo

Where does the generated control graph can be seen?
The tutorial says that tranformed classes are in sootified/avrora-small/ but I have checked that still the class file contains reflecsive calls (e.g. Avrora.class).
How can i check that reflecsive calls have been transformed.

Thanks
Jyoti Gajrani
PhD scholar
MNIT Jaipur (INDIA)

**Comment by ericbodden** [comment]
Hello. Reflective calls are not removed but augmented with "normal calls". Please take a look at our technical report for details.
